// A single page app allowing the user to play a simple game of Wheel of Fortune. 
// Use JavaScript to give the user a word to guess letter by letter. 
// optional: Will the user lose points as they guess wrong?  Will they try to beat the clock? Do they only get 3 guesses? 
// You decide! Make it clear to the user what their goal is. 
// The app should be styled with simple but modern design trends and fun for the user. 
// Remember keep your user engaged.
//several rounds of new words
// Hints are given to direct the user what the word is related to
// extra challenge: spinning wheel & money


//give user a word to guess, letter by letter
//Make it clear to the user what their goal is. (ie # guesses, buying vowels)
//RULES: guess must be be in caps

//arrays that contain the answer - change these to be generated by round function
// var game1 = ["J","A","V","A","S","C","R","I","P","T"]
// var game2 = [lovelace]

//function to generate round: words with hint
function round(word, hint){
	this.wordArray = word
	// for (var i = 0; i < word.length; i++) {
	//   wordArray = wordArray + (word[i]);
	this.hint = hint;
}

console.log(round("JAVASCRIPT", "Programming Language"));

//function guessLetter, eventhandler will be attached to each letter in the letter bank, 
//compare guess to word by iterating through word's array, award points based on # correct 
// and display correct letters

//function buyVowel, compare guess to word, deduct points $250

//function solvePuzzle attached to input field that will compare input with array, 
//all caps converts string to array



//BONUS: function spinWheel - generate random point values, bankrupt